mod "stdlib",
  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod "apt",
  :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "puppi",
  :git => "https://github.com/example42/puppi.git"

mod "jboss",
#  :git => "git@github.com:example42/puppet-jboss.git"
   :git => "https://github.com/signed/puppet-jboss"
   :ref => 'jboss-7-instance'

mod "java",
  :git => "git@github.com:puppetlabs/puppetlabs-java.git"
