# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu-14.04"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"

  # cachier plugin for vagrant
  config.cache.auto_detect = true
  #config.cache.enable_nfs  = true
  config.vm.network "public_network"

  config.vm.hostname = 'jboss-puppet'

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.provision :shell, :path => "shell/add-puppet-labs-repository.sh"

  config.vm.provision :puppet do |puppet|
    puppet.module_path = ["puppet/library/", "puppet/modules"]
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "site.pp"
#    puppet.options = ["--verbose", "--debug"]
  end
end
