# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise64-latest"

  # cachier plugin for vagrant
  config.cache.auto_detect = true
  #config.cache.enable_nfs  = true

  config.vm.provision :shell, :path => "shell/add-puppet-labs-repository.sh"

  config.vm.provision :puppet do |puppet|
    puppet.module_path = ["puppet/library/", "puppet/modules"]
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "site.pp"
    puppet.options = "--verbose --debug"
  end
end
